# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0

name: General Issue
description: Report a general issue that doesn't fit other categories
title: '[General]: '
labels: ['triage']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! This form is for general issues that don't fit into the bug report or feature request categories.
        
        Before submitting, please search through existing issues to avoid duplicates.

  - type: dropdown
    id: issue-type
    attributes:
      label: Issue type
      description: What type of issue are you reporting?
      options:
        - Question
        - Documentation
        - Content issue
        - Performance
        - Accessibility
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of the issue.
      placeholder: Please describe the issue in detail...
    validations:
      required: true

  - type: input
    id: url
    attributes:
      label: URL
      description: The URL related to this issue (if applicable).
      placeholder: https://changelog.opentelemetry.io/...

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the issue here.

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: If you have ideas about how to solve this issue, please share them here.
      placeholder: I think this could be solved by...

  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0